name: lineageXpress_parallel
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bwa
  - samtools
  - gatk4
  - openjdk=17
  - pip
  - pip:
      - tqdm
